## Natural language technology

In [47]:
import pandas as pd

## read the data set

In [48]:
df = pd.read_csv(r'/home/ali/Desktop/train.csv')

In [49]:
df

,title,subgroup,abstract,body
0,پلیس: جرائم خشن و مسلحانه در تهران کاهش یافته است,عمومی,آمارهای پلیس نشان می‌دهد که جرائم خشن و مسلحان...,رئیس پلیس آگاهی تهران بزرگ اعلام کرد که موضوع ...
1,"وزیر بهداشت:\r\nآغاز اجرای طرح جامع ""دارویار""/...",اخبار سلامت,هدف اصلی وزارت بهداشت از این طرح این است که پو...,"وزیر بهداشت جزییات طرح ""دارویار"" که اجرای آن آ..."
2,وزارت بهداشت: قیمت دارو برای مصرف کننده ثابت م...,اجتماعی,NaN,سخنگوی وزارت بهداشت، درمان و آموزش پزشکی در تو...
3,معاون رئیسی: مردم به زودی شاهد اثرات مثبت اقدا...,سیاسی,معاون امور مجلس رئیس جمهور: استان گیلان دارای ...,معاون رئیس جمهور گفت: دولت برنامه های راهبردی ...
4,دستگیری سارق ۲۰ هزار دلاری ارز دیجیتال در گلستان,اجتماعی,شهروندان توصیه‌های پلیس فتا را جدی بگیرند و در...,رییس پلیس فتا فرماندهی انتظامی گلستان گفت: سار...
...,...,...,...,...
237879,معاون وزیر ارشاد: مخالف انحصار صداوسیما هستیم,سیاسی,قطعا با هرگونه انحصار در فعالیت‌های فراگیر مرد...,معاون مطبوعاتی وزیر ارشاد گفت: انحصار صدور مجو...
237880,دیدار دست‌اندرکاران همایش حکیم تهران با مقام م...,سیاسی,حذف فلسفه از حوزه علمیه قم موجب خواهد شد افراد...,پایگاه اطلاع رسانی مقام معظم رهبری نوشت: بیانا...
237881,ترامپ: هنگام امضای برجام باید به سوریه و یمن ن...,سیاست خارجی,ترامپ برجام را یک توافق بد توصیف و تصریح کرد: ...,رئیس‌جمهور آمریکا بار دیگر با انتقاد از برجام ...
237882,واردات گوشی تلفن همراه از خودرو جلو زد,اقتصادی,در فروردین ماه امسال­­ تعداد 249 هزار و 154 دس...,براساس آمار گمرک ایران در­ فروردین ماه امسال ­...
237883,نرخ بیکاری جوانان بیش از 25 درصد است,اقتصادی,اولین گام مهم و مورد نیاز ترمیم بنگاه های در ح...,حمید حاج اسماعیلی کارشناس کار و تحلیلگر اقتصاد...

In [50]:
value_see = df['subgroup'].value_counts()

In [51]:
value_see

subgroup
اجتماعی                  74811
بین الملل                37954
سیاسی                    28737
اقتصادی                  27380
ورزشی                    17807
فرهنگی/هنری              10814
سیاست خارجی               7959
حوادث                     7649
سلامت                     6937
خواندنی ها و دیدنی ها     6618
عمومی                     4829
فناوری و IT               2193
علمی                      1850
روانشناسی                  497
اخبار سلامت                496
محیط زیست                  436
سرگرمی                     310
دانلود                     258
سفر و تفریح                142
داستان کوتاه               135
آشپزی                       29
کاربران                     25
پیامک                       18
Name: count, dtype: int64

In [52]:
value_specific_social = df[df['subgroup']=='اجتماعی']

In [53]:
value_specific_social.head()

,title,subgroup,abstract,body
2,وزارت بهداشت: قیمت دارو برای مصرف کننده ثابت م...,اجتماعی,NaN,سخنگوی وزارت بهداشت، درمان و آموزش پزشکی در تو...
4,دستگیری سارق ۲۰ هزار دلاری ارز دیجیتال در گلستان,اجتماعی,شهروندان توصیه‌های پلیس فتا را جدی بگیرند و در...,رییس پلیس فتا فرماندهی انتظامی گلستان گفت: سار...
9,پلیس فتا: تشدید مقابله با لایوهای غیر اخلاقی د...,اجتماعی,رصد این گونه جریانات غیر اخلاقی که مغایر با شئ...,معاون فرهنگی اجتماعی پلیس فتا فراجا از تشدید ط...
13,سخنان درست رحیم‌پور ازغدی و قالیباف دربارۀ مسأ...,اجتماعی,« اشتباه کردیم حجاب را بین صفر و صد محدود کردی...,- کانال تلگرام قرارگاه سایبری عمار ویدیوی یکی...
17,گزارش روزنامه «اعتماد» از تقلب در کنکور ۱۴۰۰,اجتماعی,در یکی از مهم‌ترین و امن‌ترین آزمون‌های سراسری...,روزنامه اعتماد در گزارشی مدعی شده است شماری از...

In [54]:
value_specific_international = df[df['subgroup']=='بین الملل']

In [55]:
value_specific_international.head()

,title,subgroup,abstract,body
14,به کعبه دست نزنید!,بین الملل,اما در شهر مدینه و در مسجدالنبی و قبرستان بقیع...,عربستان اگر چه حج را پس از دو سال با کمترین مح...
25,اوکراین روابط خود را با سوریه قطع کرد,بین الملل,لازم به ذکر است که وزارت خارجه سوریه پیش از ای...,رئیس جمهور اوکراین از قطع روابط این کشور با سو...
26,واکنش سازمان ملل به تصمیم سوریه در به‌ رسمیت ش...,بین الملل,وزارت خارجه سوریه روز چهارشنبه از تصمیم خود بر...,سازمان ملل به تصمیم دولت سوریه برای به رسمیت ش...
35,نیویورک تایمز: ترامپ به‌ زودی نامزدیش در انتخا...,بین الملل,نیویورک تایمز علت این اقدام ترامپ را رقابت با ...,دونالد ترامپ در نظر دارد به منظور منحرف کردن ت...
50,دولت جدید در اسرائیل/ کنست منحل شد / انتخابات ...,بین الملل,سه شنبه ، کنست اولین قرائت را برای انحلال خود ...,رسانه‌های اسرائیل منتظر اعلام رسمی انحلال کنست...

In [56]:
value_specific_political = df[df['subgroup']=='سیاسی']

In [57]:
value_specific_political.head()

,title,subgroup,abstract,body
3,معاون رئیسی: مردم به زودی شاهد اثرات مثبت اقدا...,سیاسی,معاون امور مجلس رئیس جمهور: استان گیلان دارای ...,معاون رئیس جمهور گفت: دولت برنامه های راهبردی ...
6,معاون وزیر اطلاعات: فضای مجازی بلای خانمان سوز...,سیاسی,مقام معظم رهبری بیان کردند اگر رهبر نبودند مسئ...,معاون سیاسی، فرهنگی و اجتماعی وزارت اطلاعات گف...
7,آبکش شدن با 60 گلوله پلیس؛ تاوان فرار یک جوان ...,سیاسی,خانواده این جوان 25 ساله آمریکایی گفته اند رفت...,یک جوان سیاه پوست در شهر آکرون ایالت اوهایو آم...
18,چرا بهشتی دستور آزادی همسر و دختر بازداشتی بنی...,سیاسی,شهید بهشتی فرمود آزادشان کنید، آدم، رقیب سیاسی...,ایرنا نوشت : استاد حوزه و دانشگاه با اشاره به ...
21,قرارگاه خاتم‌الانبیاء سپاه، پیمانکار راه‌آهن ا...,سیاسی,وی اضافه کرد: طبق توافق صورت گرفته، مقرر شد که...,نماینده مردم اردبیل، نمین، نیر و سرعین در مجلس...

In [58]:
value_specific_economic = df[df['subgroup']=='اقتصادی']

In [59]:
value_specific_economic.head()

,title,subgroup,abstract,body
12,هزینه خانوار در شش سال گذشته چند برابر شد؟ / ف...,اقتصادی,دهک دوم و اول (پایین‌ترین دهک‌های هزینه‌ای) بی...,اقتصاد ایران طی چند سال گذشته یکی از شدیدترین ...
24,"صادرات واکسن ""کوو ایران برکت"" به ونزوئلا",اقتصادی,۱۰۰ هزار دوز واکسن «کوو ایران برکت» به ونزوئلا...,با امضای تفاهم نامه بین « اکبر برندگی » رئیس گ...
29,تورم روپیه هند را به نابودی کشاند,اقتصادی,روپیه تاکنون در سال جاری بیش از ۶ درصد در براب...,روپیه هند برای دومین جلسه متوالی به دلیل نگران...
51,وزیر اقتصاد: کالای ته لنجی به رسمیت شناخته می‌شود,اقتصادی,خاندوزی افزود: به عبارتی معلوم شود که این اقلا...,احسان خاندوزی وزیر امور اقتصادی و دارایی در جر...
52,صادرات گل‌گاوزبان از مازندران به پاکستان,اقتصادی,آرام بخشی، درمان کم خونی، تهوع و درمان سرماخور...,مدیر جهاد کشاوزی شهرستان نکا سید شبر موسوی با ...

In [60]:
value_specific_sports = df[df['subgroup']=='ورزشی']

In [61]:
value_specific_sports.head()

,title,subgroup,abstract,body
69,اولین زن عربستانی فعال در اتوکراس (+فیلم),ورزشی,ایده تلاش برای رانندگی اتوکراس توسط زنان سعودی...,پس از اعطای گواهینامه رانندگی به زنان توسط عرب...
93,بصره، میزبان جام خلیج فارس شد,ورزشی,این رقابت ها هر دو سال یک بار با حضور ۸ کشور ع...,بیست و پنجمین دوره جام کشورهای حوزه خلیج فارس ...
97,اولین پیروزی تاریخ هندبال بانوان ایران در مساب...,ورزشی,تیم هندبال جوانان ایران با پیروزی مقابل مکزیک ...,تیم هندبال دختران ایران توانست با برتری برابر ...
123,سید جلال حسینی مربی پرسپولیس شد,ورزشی,سید جلال حسینی کاپیتان ارزشمند تیم فوتبال پرسپ...,قرارداد کاپیتان سابق پرسپولیس و محمد عسگری مرب...
142,نادرترین دختر ملی‌پوش فوتبال جهان (عکس),ورزشی,کارسون پیکت مدافع ۲۸ ساله آمریکایی که بدون داش...,فرارو: کارسون پیکوت به اولین بازیکن تاریخ فوتب...

In [62]:
value_specific_Cultural_artistic = df[df['subgroup']=='فرهنگی/هنری']

In [63]:
value_specific_Cultural_artistic.head()

,title,subgroup,abstract,body
11,تمدید نظرسنجی مردمی جشنواره فیلم‌های ورزشی تا ...,فرهنگی/هنری,بهترین‌های ورزش تلویزیون در نظرسنجی سیزدهمین ج...,به گزارش روابط عمومی جشنواره، سیزدهمین جشنواره...
20,درگذشت یکی از تاثیرگذارترین کارگردانان تئاتر جهان,فرهنگی/هنری,از بروک به عنوان یک نابغه در دنیای تئاتر یاد م...,پیتر بروک اسطوره تئاتر جهان در سن ۹۷ سالگی درگ...
32,تکذیب انحلال باشگاه خبرنگاران جوان,فرهنگی/هنری,باشگاه خبرنگاران جوان متعلق به صدا و سیما با ا...,باشگاه خبرنگاران جوان متعلق به صدا و سیما با ا...
47,"عذرخواهی خالق سریال معروف ""فرندز"" ؛ به نژادهای...",فرهنگی/هنری,پس از اتفاقی که برای جورج فلوید افتاد شروع کرد...,خالق سریال «فرندز» به خاطر بی‌توجهی به تنوع نژ...
53,اکران «برادران لیلا» در فرانسه,فرهنگی/هنری,ترانه علیدوستی، نوید محمدزاده، سعید پورصمیمی، ...,همزمان با انتشار نخستین تیزر فیلم «برادران لیل...

In [64]:
value_specific_foreign_policy = df[df['subgroup']=='سیاست خارجی ']

In [69]:
value_specific_Events = df[df['subgroup']=='حوادث']

In [70]:
value_specific_Events.head()

,title,subgroup,abstract,body
8,درگذشت دانشجوی دانشگاه فرهنگیان,حوادث,"""متین حبیب لی"" دانشجومعلم رشته آموزش ابتدایی ۹...",دانشگاه فرهنگیان با صدور پیامی، درگذشت یکی از ...
10,زاهدان/ غرق شدن 3 کودک در ظروف ذخیره آب خانگی,حوادث,گاهی مردم با قطعی آب روبه رو هستند. از این رو ...,بر اثر افت فشار و یا قطعی آب در برخی نقاط حاشی...
16,زلزله شدید در هرمزگان/ تمام ادارات دولتی امروز...,حوادث,دستگاه‌های و نهادهای امدادی، عملیاتی و خدمات ر...,ستاد بحران استانداری هرمزگان اعلام کرد: ادارات...
23,وقوع آتش‌سوزی در کیش ۵۰ درصد افزایش یافت,حوادث,حدود ۴۲ درصد از این ماموریت ها شامل ۷۱ فقره مر...,رییس اداره خدمات آتش نشانی و ایمنی جزیره کیش گ...
27,پیکر ۳۵ شهید جامانده به کشور بازگشت,حوادث,اجساد ۹ سرباز عراقی که در جنگ کشته شدند نیز تح...,همزمان با سالروز شهادت امام جواد علیه السلام پ...

In [72]:
value_specific_health = df[df['subgroup']=='سلامت']

In [73]:
value_specific_health.head()

,title,subgroup,abstract,body
15,بهترین منابع غذایی لیکوپن کدامند؟,سلامت,لیکوپن یکی از انواع کاروتنوئیدهاست که طیف رنگی...,لیکوپن در گروه آنتی‌اکسیدان‌هایی قرار می‌گیرد ...
40,این 5 علامت روی دستتان خبر از بیماری قلبی می‌دهد!,سلامت,اگر هر یک از این علائم را روی دستان خود مشاهده...,اگر چماقی شدن ناخن‌ها ناشی از بیماری قلبی باشد...
59,فوق تخصص مچ پا: کبودی و درد مچ پا را جدی بگیرید!,سلامت,NaN,NaN
79,اگر جای جوراب روی پایتان می ماند احتمالاً به ا...,سلامت,NaN,اگر احساس کردید که جوراب‌های شما روی پایتان سف...
134,علائم خاموش بیماری قلبی در سنین بالای ۵۰ سال,سلامت,ورزش با افزایش سن اهمیت بیشتری پیدا می‌کند، زی...,بیماری قلبی عامل اصلی مرگ در ایالات متحده است ...

In [76]:
value_specific_Reading_and_sightseeing = df[df['subgroup']=='خواندنی ها و دیدنی ها']

In [77]:
value_specific_Reading_and_sightseeing.head()

,title,subgroup,abstract,body
37,خروج بی‌صدا از گروه‌های واتس‌اپ چه زمانی محقق ...,خواندنی ها و دیدنی ها,خوشبختانه واتس‌اپ در حال کار برای رفع این معضل...,شاید یک گروه قدیمی باشد، اما مدام با چت‌کردن ا...
39,ناسا: خاک کره ماه متعلق به ماست، حراجش نکنید,خواندنی ها و دیدنی ها,برگزارکننده حراجی اجازه ندارد اموالی را که هنو...,حراجی گردوغبار ماه و سوسک‌هایی که خاک ماه را خ...
41,هشدار افتا درباره بدافزار چاپلین,خواندنی ها و دیدنی ها,​​​​​​​بدافزار جدیدی با نام چاپلین، به تازگی د...,بدافزار چاپلین (Chaplin)، به‌تازگی در زیرساخت‌...
42,پیش‌غذای محبوب ایرانی‌ها، جهانی شد,خواندنی ها و دیدنی ها,سالاد شیرازی، به عنوان یک سالاد ملی در ایران ش...,در اقدامی جالب و قابل توجه، صفحه رسمی مجله نیو...
44,شنای یک کوسه در شب (فیلم),خواندنی ها و دیدنی ها,در ویدئوی زیر تصویری بی‌نظیر از کوسه نهنگ Whal...,منبع: برترین‌ها

In [80]:
value_specific_general = df[df['subgroup']=='عمومی']

In [81]:
value_specific_general.head()

,title,subgroup,abstract,body
0,پلیس: جرائم خشن و مسلحانه در تهران کاهش یافته است,عمومی,آمارهای پلیس نشان می‌دهد که جرائم خشن و مسلحان...,رئیس پلیس آگاهی تهران بزرگ اعلام کرد که موضوع ...
78,زیباترین ملخ جهان (عکس),عمومی,NaN,NaN
100,با ویژگی‌های میلگرد آجدار بیشتر آشنا شوید,عمومی,NaN,NaN
102,خرید پرشروسل,عمومی,NaN,پرشروسل یا وسل به عنوان محفظه ممبران در دستگاه...
202,سیرابی لاکچری از نمای نزدیک: با پنیر رنده شده ...,عمومی,NaN,NaN

In [83]:
value_specific_Technology_and_IT = df[df['subgroup']=='فناوری و IT ']

In [85]:
value_specific_scientific = df[df['subgroup']=='علمی']

In [86]:
value_specific_scientific.head()

,title,subgroup,abstract,body
28,سالانه در کشور ۸۰ هزار نفر به فلج عصب صورت مبت...,علمی,در کشور ما تفاوت استانی در میزان شیوع این بیما...,دبیر علمی سمپوزیوم دو روزه فلج عصب صورت با بیا...
98,زنان احساساتی نیستند!,علمی,مطالعه ای جدید نشان داده است که برخلاف باور عم...,محققان معتقد هستند که برخلاف کلیشه های جنسیتی ...
105,14 تیر؛ انتشار کلید سوالات کنکور 1401,علمی,طبق اعلام سازمان سنجش، کلید اولیه سوالات آزمون...,دفترچه سوالات کنکور سراسری ۱۴۰۱ گروه آزمایشی ز...
372,دانشمندان ناسا: عکس‌های تلسکوپ جیمز وب نزدیک ب...,علمی,واقعاً سخت است که از دریچه‌ای جدید به جهان نگا...,تلسکوپ جیمز وب اکنون مشغول ثبت نخستین تصاویرش ...
380,محققان می‌خواهند با ایجاد عمیق‌ترین حفره‌ها، ا...,علمی,این تیم سپس سال آینده عمق این حفره را دوباره 1...,یک مهندس پژوهشگر از دانشگاه MIT از طریق پروژه‌...

In [87]:
value_specific_Psychology = df[df['subgroup']=='روانشناسی']

In [88]:
value_specific_Psychology.head()

,title,subgroup,abstract,body
43,نشانه‌هایی که خبر از قصد خودکشی دیگران می‌دهد,روانشناسی,NaN,رئیس کمیته پیشگیری از خودکشی انجمن روان‌پزشکان...
260,علل، علایم، عوارض و درمان خشم فروخورده,روانشناسی,خشم فروخورده ، خشمی است که ناخودآگاه انکار می ...,کمک گرفتن از مشاور و درمان میتواند به افرد کمک...
353,تقویت مثبت و تقویت منفی چیست؟,روانشناسی,هر عاملی که باعث رشد یا پیشرفت دانش آموز ( انس...,در روانشناسی رفتاری یک تقویت، معرفی یک وضعیت م...
356,۸ نشانه والدین سمی که باید از آنها آگاه بود,روانشناسی,والدین سمی در اصطلاح به والدینی گفته می‌شود که...,اگر روابط شما و فرزندتان آنطور که دوست دارید پ...
425,6 اثر افسردگی بر زندگی شخصی و کاری,روانشناسی,افسردگی بازدارنده است و باعث می‌شود افراد به‌س...,«افسردگی می‌تواند نظم زندگی را به‌ هم بزند و ش...

In [89]:
value_specific_health_news = df[df['subgroup']=='اخبار سلامت']

In [90]:
value_specific_health_news.head()

,title,subgroup,abstract,body
1,"وزیر بهداشت:\r\nآغاز اجرای طرح جامع ""دارویار""/...",اخبار سلامت,هدف اصلی وزارت بهداشت از این طرح این است که پو...,"وزیر بهداشت جزییات طرح ""دارویار"" که اجرای آن آ..."
65,روند ابتلا به کرونا در ایران افزایشی شد,اخبار سلامت,وزارت بهداشت: از همکاران پزشک خود درخواست می ک...,رئیس مرکز مدیریت بیماری های واگیر وزارت بهداشت...
154,ذخیره استراتژیک بیش از ۴۰ میلیون دز واکسن کرون...,اخبار سلامت,طبق قانون هر واکسنی که تولید شود، تاریخ انقضا ...,عضو کمیته واکسیناسیون کرونا با اشاره به اینکه ...
248,خبر خوب/ کشف داروی درمانی برای ریزش مو,اخبار سلامت,دانشمندان این را به عنوان شواهد بالینی امیدوار...,دانشمندان به یک کشف کلیدی در مورد ریزش مو و ام...
258,کردستان/ تعداد مبتلایان به وبا به ۳۰ نفر رسید,اخبار سلامت,این افراد مبتلا کسانی هستند که سابقه مسافرت خا...,معاون بهداشتی دانشگاه علوم پزشکی کردستان گفت: ...

In [91]:
value_specific_Environment = df[df['subgroup']=='محیط زیست']

In [92]:
value_specific_Environment.head()

,title,subgroup,abstract,body
5,رونمایی از آمبولانس حیات وحش استان بوشهر,محیط زیست,از همین رو پیشنهاد احداث یک واحد درمان و نقاهت...,در آئینی با حضور مدیرعامل صندوق ملی محیط زیست،...
224,انقراض نسل بیش از ۵۰۰ گونه جانوری در ۵۰ سال اخیر,محیط زیست,به نظر پژوهشگران این موضوع که بیشتر این گونه‌ه...,پژوهشگران اعلام کردند نسل بیش از ۵۰۰ گونه‌ حیو...
246,البرز/ وزش باد شدید و گردو خاک در پیش است,محیط زیست,احتمال شکستگی درختان، آسیب به سقف خانه ها و س...,مدیرکل هواشناسی استان البرز اعلام کرد: از جمعه...
681,تلف شدن یک خرس قهوه‌ای در کرج,محیط زیست,احداث روگذر یکی از تدابیری است که می تواند در ...,رییس اداره حفاظت محیط زیست شهرستان کرج از تلف ...
734,احتمال اوج‌گیری مجدد غبار آلودگی هوا,محیط زیست,استان‌های سیستان وبلوچستان، خراسان جنوبی، سمنا...,یک کارشناس هواشناسی با بیان اینکه گرد و غبار د...

In [94]:
value_specific_entertainment = df[df['subgroup']=='سرگرمی']

In [95]:
value_specific_entertainment.head()

,title,subgroup,abstract,body
552,عکسی کمیاب از بابی فیشر و رقابت همزمان با 50 نفر!,سرگرمی,بابی فیشر استاد بزرگ شطرنج آمریکایی، در سال 19...,NaN
601,اندازه جالب سیارات اگر میوه بودند! (عکس),سرگرمی,NaN,NaN
680,یک نکته جالب در زبان انگلیسی! (عکس),سرگرمی,NaN,NaN
771,نمایی دیدنی از هسته کهکشان راه شیری(عکس),سرگرمی,عکسی بسیار دیدنی از هسته کهکشان راه شیری که از...,NaN
792,نویسنده داستان‌های ترسناک چه فیلمی را نتوانست ...,سرگرمی,«من در بزرگسالی تنها از دیدن ادامه یک فیلم منص...,استیون کینگ، یکی از مشهورترین نویسندگان داستان...

In [96]:
value_specific_Download = df[df['subgroup']=='دانلود']

In [97]:
value_specific_Download.head()

,title,subgroup,abstract,body
441,دانلود بازی امپراطوری جهانی 2027 - World Empire,دانلود,World Empire 2027 به شدت اعتیاد آور است و گیم ...,World Empire 2027 یک بازی زیبا و سرگرم کننده د...
3490,دانلود بازی ماینکرافت برای موبایل - Minecraft,دانلود,در بازی Minecraft شما به صورت آزادانه به ساخت ...,از محبوب ترین، پرطرفدارترین و سرگرم کننده ترین...
3498,نرم افزار کنترل کامپیوتر (AnyDesk),دانلود,نرم افزار AnyDesk بسیار کم حجم و قابل حمل نیز ...,نرم افزار کاربردی که به شما امکان کنترل کامپیو...
6791,دانلود مرورگر موزیلا فایرفاکس - Mozilla Firefox,دانلود,آخرین نسخه مرورگر موزیلا فایرفاکس برای تمامی س...,NaN
7477,دانلود بازی زامبی ها و گیاهان - Plants vs Zomb...,دانلود,Plants vs Zombies حتی به خاطر محبوبیت بالا برا...,که به صورت اختصار آن را PvZ 3 نیز می نامند، سو...

In [98]:
value_specific_Travel_and_entertainment = df[df['subgroup']=='سفر و تفریح']

In [99]:
value_specific_Travel_and_entertainment.head()

,title,subgroup,abstract,body
1069,تسکالتوبو؛ شهری متروک اما جذاب برای مردم شوروی...,سفر و تفریح,تسکالتوبو برای نخبگان حزب کمونیست از جمله ژوزف...,زمانی که در سال 1991 فرو پاشید، شهر تفریحی در ...
2028,قارچ خور واقعی؛ هدیه نینتندو به طرفداران این خ...,سفر و تفریح,قارچ خور معروف در ایران و یا دقیق تر بگوئیم با...,پارک موضوعی پس از سال ها توسعه و چند تاخیر سرا...
4083,تور مالزی، تور هند و تور تایلند مهم‌ترین مقاصد...,سفر و تفریح,NaN,کشورهای بسیار زیادی در آسیا هستند که برای سفر ...
4688,رزرو بهترین هتل پنج ستاره در دبی,سفر و تفریح,NaN,NaN
6539,دعوت مالزی از گردشگران ایرانی: گردشگری حلال و ...,سفر و تفریح,مالزی در دو سال گذشته از فرصت استفاده کرد و بی...,مرزهای مالزی از حدود یک ماه پیش، پس از وقفه‌ای...

In [101]:
value_specific_short_story = df[df['subgroup']=='داستان کوتاه']

In [102]:
value_specific_short_story.head()

,title,subgroup,abstract,body
20326,داستان ابزار شیطان,داستان کوتاه,شیطان خود را به شکل چشمگیری به نمایش گذاشت. ای...,گویند روزی شیطان همه جا جار زد که قصد دارد از ...
25570,داستان حاکم، سیب، کشاورز و باقی قضایا,داستان کوتاه,NaN,روزی حاکمی در قصر نشسته بود که از بیرون قصر صد...
33760,داستان کوتاه فقط یک سال زنده ای,داستان کوتاه,آنتونی برجس، (رمان‌نویس معروف انگلیسی) و دوبرا...,آنتونی برجس ٤۰ ساله بود که دکترها به وی گفتند ...
46046,داستان بطری دارو,داستان کوتاه,پس از ۱۱ سال زوجی صاحب فرزند پسری شدند. آن دو ...,پس از ۱۱ سال زوجی صاحب فرزند پسری شدند. آن دو ...
51992,داستان سیل در دهكده,داستان کوتاه,NaN,روزی به خاطر وقوع زنان و کودکان شیوانا، در...

In [104]:
value_specific_cooking = df[df['subgroup']=='آشپزی']

In [105]:
value_specific_cooking.head()

,title,subgroup,abstract,body
17516,طرز تهیه شیرینی خانگی برای عید نوروز (فیلم)/ ش...,آشپزی,آموزش پخت شیرینی نخودچی خانگی برای عید نوروز.,منبع: مجله دیجی کالا
20321,طرز تهیه خامه کیک با سفیده تخمه مرغ,آشپزی,خامه کیک با سفیده تخمه مرغ یکی از روش های تهیه...,NaN
48739,طرز تهیه تاکو؛ غذای پرطرفدار مکزیکی,آشپزی,تاکو انواع مختلفی دارد، اما چیزی که در بین همه...,تاکو یک غذای محبوب و پرطرفدار مکزیکی است که می...
52798,طرز تهیه اسموتی هندوانه؛ نوشیدنی تابستانی,آشپزی,هندوانه، سرشار از ویتامین‌های C، A، B۱، B۵، B۶...,اسموتی‌ها جزو پرطرفدارین نوشیدنی‌ها برای تابست...
53245,طرز تهیه 2 نوع غذای رژیمی با مرغ,آشپزی,وقتی صحبت از غذای رژیمی میشود مرغ یکی از اولین...,گوشت مرغ به نسبت کالری کمی که دارد مدت زمانی ط...

In [106]:
value_specific_Users = df[df['subgroup']=='کاربران']

In [107]:
value_specific_Users.head()

,title,subgroup,abstract,body
749,پیام مخاطبان/ فروش گوشی بدون رجیستر قانونی است؟,کاربران,اگر گوشی در طی این مدت آسیب دید و بعد از یک ما...,چند روز پیش یه گوشی سامسونگ A03S از سایت دیجی ...
815,پیام مخاطبان/ بانک صادرات و ملی دسترسی ایرانیا...,کاربران,بانک ها با بستن صفحات خود در اینترنت مشکل اساس...,من مقیم کانادا هستم، قبلا به صورت آنلاین به حس...
2627,پیام مخاطبان/ صدای کتابداران کتابخانه های عموم...,کاربران,جامعه کتابداران به مثابه یک بچه سر راهی می‌مانند.,اینجانب عسگر محمدلو از کارکنان نهاد کتابخانه‌ه...
5676,پیام مخاطبان/ رفتار ناشایست کنسولگری ایرلند با...,کاربران,من تا به امروز بارها به سفارت های مختلف در داخ...,به کنسولگری ایرلند در تهران برای تحویل مدارک د...
5816,پیام مخاطبان/ اتفاقی قشنگ در نانوایی,کاربران,خوشحالم در این اوضاع بیرحم آدم هایی با این تفک...,یک اتفاقی برای من امروز افتاد که خیلی قشنگ بود...

In [108]:
value_specific_text_message = df[df['subgroup']=='پیامک']

In [109]:
value_specific_text_message.head()

,title,subgroup,abstract,body
43942,اس ام اس تبریک روز سینما,پیامک,NaN,21 شهریور روز ملی سینما بر همه ی اهالی سینما و...
48732,اس ام اس تبریک روز بزرگداشت ابوريحان بيرونی,پیامک,NaN,تعصب، چشم‌هاي‌ بینا را نابینا و گوش‌هاي‌ شنوا ...
52795,اس ام اس تبریک عید قربان,پیامک,NaN,عید قربان گشته با یلدای طولانی به یک شب این عی...
58130,اس ام اس روز ملی گل و گیاه,پیامک,NaN,گل هدیه ای ست فرو فرستاده از بهشت مردم کریمتر ...
58307,اس ام اس تبریک ازدواج,پیامک,NaN,ازدواج تنها پیوند زمینی است که در آسمانها بسته...